railsgirls-bne/railsgirls-bne.github.io

- _posts/2015-06-20-rspec.markdown
Created a new rspec doc that we will use at 2015 Rails Girls BNE weekend.
> New rspec doc

- _posts/2015-06-21-cloud9.markdown
New guide for how to set up cloud9
> new guide for cloud9 setup

- _posts/2012-04-18-app.markdown
- _posts/2015-06-21-cloud9.markdown
> cloud9 setup

- tutorial.html
> Use /ideas path instead of /index

- tutorial.html
> Make project directory consistent with cloud9

- tutorial.html
> Issue 26 mention ideas route

- tutorial.html
> move save file reference

- tutorial.html
I elected not to use the minified bootstrap because if a participant
starts poking around with some kind of CSS inspector they'll have more
fun this way.
Closes #28
> Prefer cdnjs to railsgirls for bootstrap assets

- tutorial.html
You never know when someone will try it.
> Ensure code sample will work

- tutorial.html
Also add p tags where they were missing
> Use left alignment for most content

- tutorial.html
> Remove whitespace from large pre code blocks

- tutorial.html
Resolves https://github.com/railsgirls-bne/railsgirls-bne.github.io/issues/37
> Don't initialize repository so that git push works later on.

- tutorial.html
Move instructions to continue to first slide.
> Feedback from event

- _posts/2015-11-15-sinatra-app.markdown
moved stuff around
added stuff
not sure if i did the highlight stuff correctly..... eek
lulz, bad commit message, sorry
Hey @SorchaAbel
Don't merge it just yet. I'm not 100% on it. needs further review.
> [WIP] Refactored

- _posts/2015-11-15-sinatra-app.markdown
Simple fix for a copy paste error
> Remove duplicated words: 'to start'

- _posts/2015-11-15-sinatra-app.markdown
Reverts railsgirls-bne/railsgirls-bne.github.io#87
> Revert "Add instructions to add SSH key"

- _posts/2015-11-14-cloud9_sinatra.markdown
Make it match the command listed in the sinatra guide:
http://railsgirls-bne.github.io/sinatra-app-guide#preview-in-a-browser
> Fix sinatra run command

- Gemfile.lock
- tutorial_nitrous.html
So that people don't lose their place during the tute.
> added missing target=_blank to some links

- _posts/2015-06-21-cloud9.markdown
Temp directory was called `rails5-proj` but tutorial was saying to remove `rails5_proj`.
> Fixed typo for folder name.

- tutorial.html
- Updated `rake db:migrate` to `rails db:migrate`.
- Fixed typos
- Updated the year in the tutorial to automatically show the current year.
> Updated a few things.
